sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 1KV4w8mMFnF1CG11ZOl3g6xqlGkjkrTRFH0H/VhcrErk28ntotugZeZaRbDzi45MEyZFyw97BGbyz+5CIHT404D4ELG8EgK3fGNDweoXEhqgKpdczI8h2ZQgeqQ0Qhztrp8orU6xQAKac+NXHzAVuMy1yuWJdKZ8kZBm/lav31nEQhh6oMJ9+XVe+uoP1NSXDoAPWpeF1WC4ootLzCxBlSHsK5sm/sd0uVzX1zRfiVGCe7XYXUYKT7jcFNPJDlynaKe64BBuSBdSZLgzlsWm7qLMSgzT5zwPJukUeFIqDrDZHZWY/1DtHYlNnYR6D3xmT55WVFo5U4bpGvHRyRArXE33xV4RRTSbUiJ0Y8xyqjRKx6Y5OWf2PK9adocTFqojs0HDPiJv+rn3IfQQVEnnI2TDi5INbd9Ql9CP5BtP+eaWoUCjmi2REjq5NiMtMM2E4ay0CLLAuIaxdPXfb1H/OEJQJsAvrDL0mawtwyctjMqn33BRbTNzsZEQrBMcdb4IV1e5XuUhzhkaqb2c1nuf3uCqIXt98QrGRCNLtyaCVXi8ZgHeW2Z+DUvx+8ULkA7dqBaqUrd75H27W2zIpIL607u7R8K8tCWc4B9Xv2fC7lwV1YkXezdqhHcK5WIgfBaz+01S8YkR3v/t1mUiWRu0+/KBITcYcyaPJ1w5tiQx9LY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Gold-of-the-Gods_5149
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy